apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
  labels:
    {{- include "kubemq-test-drive.labels" . | nindent 4 }}
    app: sender
  name: sender

spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sender
        version: {{ .Chart.AppVersion }} ## XXXXX
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}    
      containers:
      - image: "{{ .Values.senderImage }}"
        imagePullPolicy: {{ .Values.sender.imagePullPolicy }}
        name: test-sender
