apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: kubemq-test-drive

build:
  artifacts:
  - image: sender
    context: dev/sender
  - image: receiver
    context: dev/receiver
  - image: receiver2
    context: dev/receiver2

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
      - image: sender
        context: dev/sender
        docker:
          buildArgs:
            ENV: "DEV"
        sync:
          manual:
          - src: "*.py"
            dest: "/app/"
            #strip: "dev/sender"
      - image: receiver
        context: dev/receiver
        docker:
          buildArgs:
            F_OWNER: "1000"
        # Sync requires that the dest container has tar installed. With distroless images this may be an issue
        sync:
          infer: 
          - "**/*"
      - image: receiver2
        context: dev/receiver2

deploy:
  helm:
    releases:
    - name: release1
      createNamespace: true
      artifactOverrides:
        senderImage: sender
        receiverImage: receiver
        receiver2Image: receiver2
      chartPath: ./kubemq-test-drive
      namespace: test1
      valuesFiles:
      - ./kubemq-test-drive/values.yaml

